#!/usr/bin/env bash
# Regenerate the live dev/prod status block in fleet-inventory.md from the
# Redpill attestation API. Rewrites only the text between the auto-status
# markers; the hand-curated tables are left untouched.
set -euo pipefail

API=https://api.red-pill.ai
DOC="$(cd "$(dirname "$0")" && pwd)/fleet-inventory.md"

grep -q '<!-- BEGIN auto-status -->' "$DOC"
grep -q '<!-- END auto-status -->' "$DOC"

models=$(curl -sf --max-time 30 "$API/v1/models" | jq -r '.data[].id' | grep '^phala/' | sort)

rows=""
while read -r m; do
  [ -z "$m" ] && continue
  json=$(curl -sf --max-time 30 "$API/v1/attestation/report?model=$m" || true)
  if [ -z "$json" ]; then
    img="(no report)"
  else
    img=$(printf '%s' "$json" | jq -r '
      if (.vm_config|type)=="string" then (.vm_config|fromjson|.image // "opaque (MRTD only)")
      elif ((.model_attestations[0].info.vm_config?) // null) != null
        then (.model_attestations[0].info.vm_config|fromjson|.image // "opaque (MRTD only)")
      else "opaque (MRTD only)" end')
  fi
  case "$img" in
    *-dev-*|*nvidia-dev*) status="**DEV**" ;;
    "opaque (MRTD only)"|"(no report)") status="—" ;;
    *) status="prod" ;;
  esac
  rows="${rows}| \`${m}\` | \`${img}\` | ${status} |"$'\n'
done <<< "$models"

ts=$(date -u +"%Y-%m-%d %H:%MZ")
block="<!-- BEGIN auto-status -->
<!-- regenerated by refresh-fleet-status.sh; do not hand-edit between these markers -->
### Live dev/prod status — auto-refreshed ${ts}

Regenerated from \`${API}/v1/attestation/report\` for every \`phala/*\` model.
\`—\` = image not readable from the wrapper (opaque MRTD-only shape, or no report).

| Model | OS image (live) | dev/prod |
|---|---|:-:|
${rows}<!-- END auto-status -->"

awk -v block="$block" '
  /<!-- BEGIN auto-status -->/ { print block; skip=1; next }
  /<!-- END auto-status -->/   { skip=0; next }
  !skip
' "$DOC" > "$DOC.tmp" && mv "$DOC.tmp" "$DOC"

echo "updated $DOC"
